#======================================#
#========== Server settings ===========#
#======================================#
server:
  port: 5001
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8


#======================================#
#========== Spring settings ===========#
#======================================#
spring:
  main:
    allow-bean-definition-overriding: true
  # Ӧ�ó�������
  application:
    name: cmp.portal

  # ��ǰ�������ƣ�ע�⣺��������Ϊ test ���ǵ�Ԫ����ר�õ����ƣ�
  profiles:
    active: default
#======================================#
#========== Project settings ==========#
#======================================#
logging:
  path: logs/
  level:
    com.haide.core: DEBUG
    com.haide.web: ERROR
    root: INFO

# info �����/actuator/info��
info:
  author: laymat
  email: laymat@163.com
  version: 1.0.0

# ���� actuator �������еĶ˵�
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    port: 8810
dubbo:
  server: true
  scan:
    base-packages: com.laymat.dubbo.provider
  application:
    id: dubbo-provider
    name: dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
